WebApplication6/Models/Pjesma.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace WebApplication6.Models
{
    public partial class Pjesma
    {
        public Pjesma()
        {
            PjesmaKorisniks = new HashSet<PjesmaKorisnik>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public int AlbumId { get; set; }
        public int ZanrId { get; set; }
        public DateTime GodinaIzdavanja { get; set; }

        public virtual Album Album { get; set; }
        public virtual Žanr Zanr { get; set; }
        public virtual ICollection<PjesmaKorisnik> PjesmaKorisniks { get; set; }
    }
}

WebApplication6/Controllers/PjesmasController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using Syncfusion.Pdf.Grid;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{
    public class PjesmasController : Controller
    {
        private readonly DBContext _context;

        public PjesmasController(DBContext context)
        {
            _context = context;
        }

        public ActionResult CreateDocument(string? filter, string? vrsta)

        {
            PdfFont font = new PdfStandardFont(PdfFontFamily.Helvetica, 10);
            PdfFont bigFont = new PdfStandardFont(PdfFontFamily.Helvetica, 20);

            PdfBrush brush = new PdfSolidBrush(Syncfusion.Drawing.Color.Black);
            PdfDocument doc = new PdfDocument();
            //Add a page to the document.
            PdfPage page = doc.Pages.Add();
            //Create PDF graphics for the page
            PdfGraphics graphics = page.Graphics;
            PdfGrid pdfGrid = new PdfGrid();

            //Load the image as stream.

            System.IO.FileStream imageStream = new FileStream("logo.png", FileMode.Open, FileAccess.Read);
            PdfBitmap image = new PdfBitmap(imageStream);
            graphics.DrawImage(image, 200, 200);

            //Draw the image
            Syncfusion.Drawing.RectangleF bounds = new Syncfusion.Drawing.RectangleF(0, 0, doc.Pages[0].GetClientSize().Width, 50);
            PdfPageTemplateElement header = new PdfPageTemplateElement(bounds);
            PdfCompositeField compField = new PdfCompositeField(bigFont, brush, "Izvjestaj");

            compField.Draw(header.Graphics, new Syncfusion.Drawing.PointF(120, 0));

            //Add the header at the top.

            doc.Template.Top = header;
            //Save the PDF document to stream
            //Create a Page template that can be used as footer.


            PdfPageTemplateElement footer = new PdfPageTemplateElement(bounds);



            //Create page number field.

            PdfPageNumberField pageNumber = new PdfPageNumberField(font, brush);

            //Create page count field.

            PdfPageCountField count = new PdfPageCountField(font, brush);

            //Add the fields in composite fields.

            PdfCompositeField compositeField = new PdfCompositeField(font, brush, "Stranica {0} od {1}", pageNumber, count);

            compositeField.Bounds = footer.Bounds;

            //Draw the composite field in footer.

            compositeField.Draw(footer.Graphics, new Syncfusion.Drawing.PointF(450, 40));
            //Add the footer template at the bottom.

            doc.Template.Bottom = footer;

            MemoryStream stream = new MemoryStream();
            //Add values to list
            List<object> data = new List<object>();

            if (String.IsNullOrEmpty(filter))
            {
                var Pjesme = _context.Pjesmas
                                 .AsNoTracking()
                                 .OrderBy(o => o.Id)
                                 .ToList();
                ispisi(Pjesme, data);
            }
            else
            {
                switch (vrsta)
                {


                    case "Naziv":
                        var Pjesme = _context.Pjesmas
                                .AsNoTracking()
                                .Where(n => n.Naziv.Equals(filter))
                                .OrderBy(o => o.Id)
                                .ToList();
                        ispisi(Pjesme, data);
                        break;
                    case "Album":
                        var album = _context.Albums.AsNoTracking().Where(o => o.Naziv.Equals(filter)).ToList();
                        Pjesme = _context.Pjesmas.AsNoTracking().Where(p => p.AlbumId.Equals(album[0].Id)).ToList();
                        ispisi(Pjesme, data);
                        break;
                    case "Žanr":
                        var zanr = _context.Žanrs.AsNoTracking().Where(o => o.Ime.Equals(filter)).ToList();
                        Pjesme = _context.Pjesmas.AsNoTracking().Where(p => p.AlbumId.Equals(zanr[0].Id)).ToList();

                        ispisi(Pjesme, data);
                        break;

                }
            }
            //Add list to IEnumerable
            IEnumerable<object> dataTable = data;
            //Assign data source.
            pdfGrid.DataSource = dataTable;
            pdfGrid.Draw(page, new Syncfusion.Drawing.PointF(50, 50));
            doc.Save(stream);
            //If the position is not set to '0' then the PDF will be empty.
            stream.Position = 0;
            //Close the document.
            doc.Close(true);
            //Defining the ContentType for pdf file.
            string contentType = "application/pdf";
            //Define the file name.
            string fileName = "Output.pdf";

            return File(stream, contentType, fileName);
        }
        public void ispisi(List<Pjesma> Pjesme, List<object> data)
        {
            foreach (var Pjesma in Pjesme)
            {
                var album = _context.Albums.AsNoTracking().Where(o => o.Id.Equals(Pjesma.AlbumId)).ToList();
                var zanr = _context.Žanrs.AsNoTracking().Where(o => o.Id.Equals(Pjesma.ZanrId)).ToList();
                var prodane = _context.PjesmaKorisniks.AsNoTracking().Where(e => e.PjesmaId.Equals(Pjesma.Id)).ToList();

                var row = new { Naziv = Pjesma.Naziv, Datum = Pjesma.GodinaIzdavanja, Album = album[0].Naziv, Zanr = zanr[0].Ime, Broj_Prodanih = prodane.Count  };
                data.Add(row);



            }
        }


        // GET: Pjesmas
        public async Task<IActionResult> Index()
        {
            var dBContext = _context.Pjesmas.Include(p => p.Album).Include(p => p.Zanr);
            return View(await dBContext.ToListAsync());
        }

        // GET: Pjesmas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pjesma = await _context.Pjesmas
                .Include(p => p.Album)
                .Include(p => p.Zanr)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pjesma == null)
            {
                return NotFound();
            }

            return View(pjesma);
        }

        // GET: Pjesmas/Create
        public IActionResult Create()
        {
            ViewData["AlbumId"] = new SelectList(_context.Albums, "Id", "Naziv");
            ViewData["ZanrId"] = new SelectList(_context.Žanrs, "Id", "Ime");
            return View();
        }

        // POST: Pjesmas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv,AlbumId,ZanrId,GodinaIzdavanja")] Pjesma pjesma)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(pjesma);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AlbumId"] = new SelectList(_context.Albums, "Id", "Naziv", pjesma.AlbumId);
            ViewData["ZanrId"] = new SelectList(_context.Žanrs, "Id", "Ime", pjesma.ZanrId);
            return View(pjesma);
        }

        // GET: Pjesmas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pjesma = await _context.Pjesmas.FindAsync(id);
            if (pjesma == null)
            {
                return NotFound();
            }
            ViewData["AlbumId"] = new SelectList(_context.Albums, "Id", "Naziv", pjesma.AlbumId);
            ViewData["ZanrId"] = new SelectList(_context.Žanrs, "Id", "Ime", pjesma.ZanrId);
            return View(pjesma);
        }

        // POST: Pjesmas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naziv,AlbumId,ZanrId,GodinaIzdavanja")] Pjesma pjesma)
        {
            if (id != pjesma.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pjesma);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PjesmaExists(pjesma.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AlbumId"] = new SelectList(_context.Albums, "Id", "Naziv", pjesma.AlbumId);
            ViewData["ZanrId"] = new SelectList(_context.Žanrs, "Id", "Ime", pjesma.ZanrId);
            return View(pjesma);
        }

        // GET: Pjesmas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pjesma = await _context.Pjesmas
                .Include(p => p.Album)
                .Include(p => p.Zanr)
                .FirstOrDefaultAsync(m => m.Id == id);

WebApplication6/Views/Pjesmas/Create.cshtml
@model WebApplication6.Models.Pjesma

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pjesma</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlbumId" class="control-label"></label>
                <select asp-for="AlbumId" class="form-control" asp-items="ViewBag.AlbumId"></select>
                <span asp-validation-for="AlbumId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZanrId" class="control-label"></label>
                <select asp-for="ZanrId" class="form-control" asp-items="ViewBag.ZanrId"></select>
                <span asp-validation-for="ZanrId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GodinaIzdavanja" class="control-label"></label>
                <input asp-for="GodinaIzdavanja" class="form-control" />
                <span asp-validation-for="GodinaIzdavanja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication6/Views/Pjesmas/Delete.cshtml
@model WebApplication6.Models.Pjesma

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pjesma</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GodinaIzdavanja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GodinaIzdavanja)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Album)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Album.Naziv)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zanr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zanr.Ime)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication6/Views/Pjesmas/Details.cshtml
@model WebApplication6.Models.Pjesma

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pjesma</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GodinaIzdavanja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GodinaIzdavanja)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Album)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Album.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zanr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zanr.Ime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication6/Views/Pjesmas/Edit.cshtml
@model WebApplication6.Models.Pjesma

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pjesma</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlbumId" class="control-label"></label>
                <select asp-for="AlbumId" class="form-control" asp-items="ViewBag.AlbumId"></select>
                <span asp-validation-for="AlbumId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZanrId" class="control-label"></label>
                <select asp-for="ZanrId" class="form-control" asp-items="ViewBag.ZanrId"></select>
                <span asp-validation-for="ZanrId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GodinaIzdavanja" class="control-label"></label>
                <input asp-for="GodinaIzdavanja" class="form-control" />
                <span asp-validation-for="GodinaIzdavanja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication6/Views/Pjesmas/Index.cshtml
@model IEnumerable<WebApplication6.Models.Pjesma>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a type="button" class="btn btn-primary" asp-action="Create">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square" viewBox="0 0 16 16">
            <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
        </svg> Unesi Novu Pjesmu
    </a>

    <a asp-controller="PjesmaKorisniks" asp-action="Index" style="margin-top:5px;" type="button" class="btn btn-outline-success btn-lg btn-block">Prodane pjesme</a>

    <div class="container">
        <form asp-controller="Pjesmas" asp-action="CreateDocument" method="get">
            <div class="row">
                <div class="col-sm">
                    <select class="form-control" name="vrsta">
                        <option selected>Odaberite kategoriju za filter</option>
                        <option value="Naziv">Naziv</option>
                        <option value="Album">Album</option>
                        <option value="Zanr">Zanr</option>
                    </select>
                </div>
                <div class="col-sm">
                    <input type="text" class="form-control" placeholder="Popunite polje za filter" name="filter">
                </div>
                <div class="col-sm">

                    <button type="submit" class="btn btn-dark">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-pdf" viewBox="0 0 16 16">
                            <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z" />
                            <path d="M4.603 14.087a.81.81 0 0 1-.438-.42c-.195-.388-.13-.776.08-1.102.198-.307.526-.568.897-.787a7.68 7.68 0 0 1 1.482-.645 19.697 19.697 0 0 0 1.062-2.227 7.269 7.269 0 0 1-.43-1.295c-.086-.4-.119-.796-.046-1.136.075-.354.274-.672.65-.823.192-.077.4-.12.602-.077a.7.7 0 0 1 .477.365c.088.164.12.356.127.538.007.188-.012.396-.047.614-.084.51-.27 1.134-.52 1.794a10.954 10.954 0 0 0 .98 1.686 5.753 5.753 0 0 1 1.334.05c.364.066.734.195.96.465.12.144.193.32.2.518.007.192-.047.382-.138.563a1.04 1.04 0 0 1-.354.416.856.856 0 0 1-.51.138c-.331-.014-.654-.196-.933-.417a5.712 5.712 0 0 1-.911-.95 11.651 11.651 0 0 0-1.997.406 11.307 11.307 0 0 1-1.02 1.51c-.292.35-.609.656-.927.787a.793.793 0 0 1-.58.029zm1.379-1.901c-.166.076-.32.156-.459.238-.328.194-.541.383-.647.547-.094.145-.096.25-.04.361.01.022.02.036.026.044a.266.266 0 0 0 .035-.012c.137-.056.355-.235.635-.572a8.18 8.18 0 0 0 .45-.606zm1.64-1.33a12.71 12.71 0 0 1 1.01-.193 11.744 11.744 0 0 1-.51-.858 20.801 20.801 0 0 1-.5 1.05zm2.446.45c.15.163.296.3.435.41.24.19.407.253.498.256a.107.107 0 0 0 .07-.015.307.307 0 0 0 .094-.125.436.436 0 0 0 .059-.2.095.095 0 0 0-.026-.063c-.052-.062-.2-.152-.518-.209a3.876 3.876 0 0 0-.612-.053zM8.078 7.8a6.7 6.7 0 0 0 .2-.828c.031-.188.043-.343.038-.465a.613.613 0 0 0-.032-.198.517.517 0 0 0-.145.04c-.087.035-.158.106-.196.283-.04.192-.03.469.046.822.024.111.054.227.09.346z" />
                        </svg> Napravi PDF
                    </button>

                </div>
            </div>
        </form>
    </div>


</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naziv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GodinaIzdavanja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Album)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zanr)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GodinaIzdavanja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Album.Naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Zanr.Ime)
                </td>
                <td>
                    <a type="button" class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg> Uredi
                    </a>
                    <a type="button" class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-square" viewBox="0 0 16 16">
                            <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                            <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                        </svg> Detalji
                    </a>
                    <a type="button" class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg> Izbriši
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>